services:
  #db:
  #  image: postgres
  #  restart: unless-stopped
  #  environment:
  #    POSTGRES_PASSWORD: secret
  #  volumes:
  #    - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
  app:
    build:
      context: .
    environment:
      #REFLEX_DB_URL: postgresql+psycopg://postgres:secret@db/postgres
      REFLEX_REDIS_URL: redis://redis:6379
    ports:
      - 8080:8080
    volumes:
      - upload-data:/app/uploaded_files
    restart: unless-stopped

volumes:
  #postgres-data:
  # Uploaded files
  upload-data: