name: Build package

on:
  pull_request:
    branches:
      - main
      - "v[0-9]+.[0-9]+.x"
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: pip install ".[dev]"

      - name: Run Black
        run: black --check fwtv tests

      - name: Run isort
        run: isort fwtv tests -c

      - name: Run flake8
        run: flake8 fwtv tests

      - name: Run mypy
        run: mypy fwtv tests

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: linters

    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: pip install ".[test]"

      - name: Run pytest
        run: pytest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Detect release version
        if: ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+[a|b]?\d*$
        run: |
          echo FWTV_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV

      - name: Install build
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+[a|b]?\d*$
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Attach artifacts to github release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+[a|b]?\d*$
        with:
          files: |
            dist/*.whl
          prerelease: ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+[a|b]\d+$
