name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        type: string
      is_release:
        description: 'Whether this is a release build'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "tag=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
            echo "is_release=${{ inputs.is_release }}" >> $GITHUB_OUTPUT
            # Extract version without 'v' prefix for release builds
            if [ "${{ inputs.is_release }}" = "true" ]; then
              VERSION_WITHOUT_V=${inputs.image_tag#v}
              echo "version_without_v=$VERSION_WITHOUT_V" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          else
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ steps.tag.outputs.tag }},enable={{ steps.tag.outputs.is_release == 'true' }}
            type=raw,value=${{ steps.tag.outputs.version_without_v }},enable={{ steps.tag.outputs.is_release == 'true' }}
            type=raw,value=latest,enable={{ steps.tag.outputs.is_release == 'true' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image details
        run: |
          echo "Built and pushed images:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "Image digest:"
          echo "${{ steps.meta.outputs.json }}"
