name: Lint code

on:
  push:
    branches:
      - main
      - "v*"
      - "test-me-*"
    tags:
      - "v*"

  pull_request:
    branches:
      - main
      - "v*"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: pip install ".[lint]"

      - name: Run Black
        run: black --check fwtv tests

      - name: Run isort
        run: isort . -c

      - name: Run flake8
        run: flake8 fwtv tests

      - name: Run mypy
        run: mypy fwtv tests